### ISSUE TITLE
The dimensions selection widget does not compile on macOS, due to the use of <execution>

### ISSUE THREAD

**Issue by thoellt** [ManiVaultStudio/t-SNE-Analysis#27]
Apple clang does not support standardization of Parallelism TS introduced in C++17 (see https://en.cppreference.com/w/cpp/compiler_support). We should avoid using it or provide an alternative codepath for macOS.

**Comment by alxvth** [comment]
That action is now part if the point data plugin in the core. This issue is solved, and the code compiles on macOS, too, now.

https://github.com/ManiVaultStudio/core/blob/7f453479dc6170f3c0c696fa50f3000737c8269f/HDPS/src/plugins/PointData/src/DimensionsPickerAction.cpp#L403
