### ISSUE TITLE
Selecting in Image Viewer only select landmarks in specific sections of the image

### ISSUE THREAD

**Issue by JulianThijssen** [ManiVaultStudio/t-SNE-Analysis#47]
For example in the brain dataset. Only selecting in the upper portion of the image selects landmarks on top-level HSNE.
Selecting in the bottom portion of the image selects no landmarks.
![image](https://user-images.githubusercontent.com/2978176/145612391-de5eeda0-c115-4876-8874-fd38c36449e7.png)

**Comment by alxvth** [comment]
I also cannot reproduce this anymore. Is this still a problen, @JulianThijssen?

**Comment by JulianThijssen** [comment]
Yep, seems to work now.
