### ISSUE TITLE
HSNE & TSNE analyses info panels show two dimensions pickers

### ISSUE THREAD

**Issue by ThomasKroes** [ManiVaultStudio/t-SNE-Analysis#62]

**Comment by alxvth** [comment]
I think this was solved with https://github.com/ManiVaultStudio/t-SNE-Analysis/commit/a366722adb4dce0a430cc534713dd255fa0a0b31, https://github.com/ManiVaultStudio/t-SNE-Analysis/commit/2d2cf55669c537911c54c3e1485e8d6d0da289be and https://github.com/ManiVaultStudio/t-SNE-Analysis/commit/7a52e0a680f2e33f5f8a2717fedb40887586feb1 , @ThomasKroes?

**Comment by ThomasKroes** [comment]
> I think this was solved with [a366722](https://github.com/ManiVaultStudio/t-SNE-Analysis/commit/a366722adb4dce0a430cc534713dd255fa0a0b31), [2d2cf55](https://github.com/ManiVaultStudio/t-SNE-Analysis/commit/2d2cf55669c537911c54c3e1485e8d6d0da289be) and [7a52e0a](https://github.com/ManiVaultStudio/t-SNE-Analysis/commit/7a52e0a680f2e33f5f8a2717fedb40887586feb1) , @ThomasKroes?

Yes this has been solved in the mean time.
