### ISSUE TITLE
Refined HSNE embeddings should be able to be recomputed / continued

### ISSUE THREAD

**Issue by JulianThijssen** [ManiVaultStudio/t-SNE-Analysis#64]

**Comment by alxvth** [comment]
This is partially addressed in #89: most refined HSNE embeddings can now be recomputed / continued - except data level embeddings (scale 0).

**Comment by alxvth** [comment]
This is now fully supported with https://github.com/ManiVaultStudio/t-SNE-Analysis/pull/94
