### ISSUE TITLE
HSNE context menue contains empty entries for connection

### ISSUE THREAD

**Issue by thoellt** [ManiVaultStudio/t-SNE-Analysis#75]
see image

<img width="813" alt="image" src="https://github.com/ManiVaultStudio/t-SNE-Analysis/assets/2159209/5f10d14f-d199-4890-9d63-59c019889d61">

**Comment by alxvth** [comment]
This is solved on the current core master branch with https://github.com/ManiVaultStudio/core/commit/98beec824c6139b131d6913befe279864e21aa70
