### ISSUE TITLE
HSNE refine does not work at all?

### ISSUE THREAD

**Issue by thoellt** [ManiVaultStudio/t-SNE-Analysis#76]
See image, bottom left is a high level embedding, top left is the result of selecting everything in that embedding and refining. The visible selection is then based on selecting everything in the top left embedding (it should cover the complete image).

<img width="2233" alt="image" src="https://github.com/ManiVaultStudio/t-SNE-Analysis/assets/2159209/8ac211f3-2e88-48f2-8354-bcc258996739">

**Comment by alxvth** [comment]
This is fixed now: those helper data sets are now by default invisible and the user only sees the actual scale data sets
