### ISSUE TITLE
HSNE dataset names should give some indication on what they are

### ISSUE THREAD

**Issue by thoellt** [ManiVaultStudio/t-SNE-Analysis#77]
any refinement of an HSNE embedding results in a new dataset called hsne_scale/HSNE Scale. It would be good to have the option to name them.

<img width="483" alt="image" src="https://github.com/ManiVaultStudio/t-SNE-Analysis/assets/2159209/1734c210-e604-49e4-a1d8-e487b510de2e">

**Comment by alxvth** [comment]
This is solved on the current master core with commit https://github.com/ManiVaultStudio/core/commit/7b3f10fd4eecef77059143ad30ee4d4725d64ec2
